#!/bin/bash

# Set java home
if [[ `uname` == "Darwin" ]]; then
    JAVA_HOME=`/usr/libexec/java_home 2>/dev/null`
elif [[ `uname` == "Linux" ]]; then
    JAVA_HOME=$(readlink -m $(dirname $(readlink -f "`which java`"))/../../)
fi

export JAVA_HOME

# Colorize maven output, courtesy of:
# http://blog.blindgaenger.net/colorize_maven_output.html
if command -v mvn >/dev/null ; then
color_maven() {
    local e=$(echo -e "\x1b")[
    local highlight="1;32m"
    local info="0;36m"
    local warn="1;33m"
    local error="1;31m"

    $(which mvn) $* | sed -e "s/Tests run: \([^,]*\), Failures: \([^,]*\), Errors: \([^,]*\), Skipped: \([^,]*\)/${e}${highlight}Tests run: \1${e}0m, Failures: ${e}${error}\2${e}0m, Errors: ${e}${warn}\3${e}0m, Skipped: ${e}${info}\4${e}0m/g" \
      -e "s/\(\[WARN\].*\)/${e}${warn}\1${e}0m/g" \
      -e "s/\(\[INFO\].*\)/${e}${info}\1${e}0m/g" \
      -e "s/\(\[ERROR\].*\)/${e}${error}\1${e}0m/g"
  }
  alias mvn=color_maven
fi
